on:
  push:
    tags:
      - "v*"
name: Create release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
      - name: Create zip file
        run: |
          zip -r contextual-alt-text.zip *.php composer.* readme.txt vendor src assets languages
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: contextual-alt-text.zip
          body_path: release-body.md
