on:
  push:
    tags:
      - 'v*'
name: Create release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - name: Build assets
        run: npm run build
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
      - name: Create zip file
        run: |
          zip -r auto-alt-text.zip *.php composer.* readme.txt dist vendor src resources languages
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: auto-alt-text.zip
          body_path: release-body.md
